const fs = require('fs');
const { execSync } = require('child_process');
const cron = require('node-cron');

// Configuration
const filePath = './generatedCode.js'; // File to modify
const repoPath = '.'; // Path to your Git repository
const commitTimes = ['0 8 * * *', '0 14 * * *', '0 20 * * *']; // 8 AM, 2 PM, 8 PM daily
const githubRepoUrl = 'https://github.com/your-username/your-repo.git'; // Replace with your repo URL

// Function to generate code with a timestamped comment
function generateCode() {
    const timestamp = new Date().toISOString();
    const codeContent = `// Auto-generated code at ${timestamp}
console.log("This is an automated update at ${timestamp}");

// Sample function to demonstrate code generation
function automatedFunction() {
    return "Generated by autoCommit.js on ${timestamp}";
}

// Export for potential use
module.exports = { automatedFunction };
`;

    try {
        fs.writeFileSync(filePath, codeContent);
        console.log(`Generated code in ${filePath} at ${timestamp}`);
    } catch (error) {
        console.error(`Error writing to file: ${error.message}`);
    }
}

// Function to execute Git commands
function executeGitCommands() {
    const timestamp = new Date().toISOString();
    try {
        // Change to repository directory
        process.chdir(repoPath);

        // Stage changes
        execSync('git add .', { stdio: 'inherit' });

        // Commit changes
        execSync(`git commit -m "Automated commit at ${timestamp}"`, { stdio: 'inherit' });

        // Push to GitHub
        execSync('git push origin main', { stdio: 'inherit' });
        console.log(`Successfully committed and pushed at ${timestamp}`);
    } catch (error) {
        console.error(`Error in Git operations: ${error.message}`);
    }
}

// Function to perform the full automation task
function automateTask() {
    console.log('Starting automation task...');
    generateCode();
    executeGitCommands();
}

// Schedule the task three times daily
commitTimes.forEach((schedule, index) => {
    cron.schedule(schedule, () => {
        console.log(`Running scheduled commit #${index + 1}...`);
        automateTask();
    });
});

// Run once immediately for testing
automateTask();

console.log('Automation script started. Waiting for scheduled times...');